# Generated by Django 3.2.4 on 2021-09-01 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interactions", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="app_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="rating",
            old_name="app_code",
            new_name="code",
        ),
    ]
