# Generated by Django 3.2.4 on 2021-09-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interactions", "0003_auto_20210901_1623"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rating",
            name="unique_rationg_created_by_app_code",
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("created_by", "code"), name="unique_rationg_created_by_code"
            ),
        ),
    ]
