# Generated by Django 3.2.4 on 2021-09-14 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAuthorization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("project_uuid", models.UUIDField()),
                (
                    "role",
                    models.PositiveIntegerField(
                        choices=[(0, "not set"), (1, "viewer"), (2, "contributor"), (3, "admin")], default=0
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, verbose_name="Created on")),
                ("modified_on", models.DateTimeField(auto_now=True, verbose_name="Modified on")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Authorization",
                "verbose_name_plural": "Project Authorizations",
                "unique_together": {("user", "project_uuid")},
            },
        ),
    ]
