# Generated by Django 3.2.4 on 2021-07-13 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppTypeAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, verbose_name="Created on")),
                ("modified_on", models.DateTimeField(auto_now=True, verbose_name="Modified on")),
                ("app_code", models.SlugField()),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("IB", "image_banner"), ("IC", "image_common"), ("AT", "attachment"), ("LK", "link")],
                        max_length=2,
                        verbose_name="Type",
                    ),
                ),
                ("attachment", models.FileField(upload_to="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_apptypeassets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modified_apptypeassets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "App Type Asset",
                "verbose_name_plural": "App Type Assets",
            },
        ),
    ]
