# Generated by Django 3.2.4 on 2021-07-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_apptypeasset"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="apptypeasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("asset_type", "IC")),
                fields=("asset_type", "app_code"),
                name="unique_asset_type_icon_app_code",
            ),
        ),
    ]
