# Generated by Django 3.2.4 on 2021-07-23 18:55

from django.db import migrations, models
import marketplace.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_apptypeasset_unique_asset_type_icon_app_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="app_code",
            field=models.SlugField(validators=[marketplace.core.validators.validate_app_code_exists]),
        ),
        migrations.AlterField(
            model_name="apptypeasset",
            name="app_code",
            field=models.SlugField(validators=[marketplace.core.validators.validate_app_code_exists]),
        ),
    ]
