# Generated by Django 3.2.4 on 2021-08-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_auto_20210723_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="config",
            field=models.JSONField(null=True),
        ),
    ]
