# Generated by Django 3.2.4 on 2021-08-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0004_auto_20210723_1555"),
    ]

    operations = [
        migrations.AddField(
            model_name="apptypeasset",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apptypeasset",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
