# Generated by Django 3.2.4 on 2021-08-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_alter_app_config"),
    ]

    operations = [
        migrations.RenameField(
            model_name="app",
            old_name="org_uuid",
            new_name="project_uuid",
        ),
    ]
