# Generated by Django 3.2.4 on 2021-08-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_auto_20210825_1855"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="project_uuid",
            field=models.UUIDField(verbose_name="Project UUID"),
        ),
    ]
