# Generated by Django 3.2.4 on 2021-08-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_rename_org_uuid_app_project_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="project_uuid",
            field=models.UUIDField(verbose_name="Project UUID"),
        ),
    ]
