# Generated by Django 3.2.4 on 2021-09-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0008_auto_20210901_1623"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="apptypeasset",
            name="unique_asset_type_icon_app_code",
        ),
        migrations.AddConstraint(
            model_name="apptypeasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("asset_type", "IC")),
                fields=("asset_type", "code"),
                name="unique_asset_type_icon_code",
            ),
        ),
    ]
