# Generated by Django 3.2.4 on 2021-09-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0009_auto_20210901_1640"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="config",
            field=models.JSONField(default=dict),
        ),
    ]
