# Generated by Django 3.2.4 on 2021-09-03 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import marketplace.core.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applications", "0010_alter_app_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppTypeFeatured",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, verbose_name="Created on")),
                ("modified_on", models.DateTimeField(auto_now=True, verbose_name="Modified on")),
                ("code", models.SlugField(validators=[marketplace.core.validators.validate_app_code_exists])),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_apptypefeatureds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modified_apptypefeatureds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AppType Featured",
                "verbose_name_plural": "AppType Featureds",
            },
        ),
        migrations.AddConstraint(
            model_name="apptypefeatured",
            constraint=models.UniqueConstraint(fields=("code",), name="unique_app_type_featured_code"),
        ),
    ]
