# Generated by Django 3.2.4 on 2021-09-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0011_auto_20210903_1613"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apptypeasset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("IB", "Image Banner"),
                    ("IC", "Icon"),
                    ("AT", "Attachment"),
                    ("LK", "Link"),
                ],
                max_length=2,
                verbose_name="Type",
            ),
        ),
    ]
