# Generated by Django 3.2.4 on 2022-08-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_app_flow_object_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apptypeasset",
            name="url",
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
    ]
