# Generated by Django 3.2.4 on 2023-07-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0014_alter_apptypeasset_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="configured",
            field=models.BooleanField(default=False),
        ),
    ]
