# Generated by Django 3.2.4 on 2023-07-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0014_alter_apptypeasset_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="apptypefeatured",
            name="priority",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
