# Generated by Django 3.2.4 on 2023-11-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_app_configured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='platform',
            field=models.CharField(choices=[('IA', 'inteligence-artificial'), ('WF', 'weni-flows'), ('RC', 'rocketchat'), ('VT', 'vtex')], max_length=2),
        ),
    ]
