# Generated by Django 3.2.4 on 2022-09-29 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applications", "0013_app_flow_object_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=60)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ACCOUNT_UPDATE", "WhatsApp.data.templates.category.account_update"),
                            ("PAYMENT_UPDATE", "WhatsApp.data.templates.category.payment_update"),
                            ("PERSONAL_FINANCE_UPDATE", "WhatsApp.data.templates.category.personal_finance_update"),
                            ("SHIPPING_UPDATE", "WhatsApp.data.templates.category.shipping_update"),
                            ("RESERVATION_UPDATE", "WhatsApp.data.templates.category.reservation_update"),
                            ("ISSUE_RESOLUTION", "WhatsApp.data.templates.category.issue_resolution"),
                            ("APPOINTMENT_UPDATE", "WhatsApp.data.templates.category.appointment_update"),
                            ("TRANSPORTATION_UPDATE", "WhatsApp.data.templates.category.transportation_update"),
                            ("TICKET_UPDATE", "WhatsApp.data.templates.category.ticket_update"),
                            ("ALERT_UPDATE", "WhatsApp.data.templates.category.alert_update"),
                            ("AUTO_REPLY", "WhatsApp.data.templates.category.auto_reply"),
                            ("TRANSACTIONAL", "WhatsApp.data.templates.category.transactional"),
                            ("MARKETING", "WhatsApp.data.templates.category.marketing"),
                            ("OTP", "WhatsApp.data.templates.category.otp"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name="Created on"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("MEDIA", "WhatsApp.data.templates.type.media"),
                            ("INTERACTIVE", "WhatsApp.data.templates.type.interactive"),
                            ("TEXT", "WhatsApp.data.templates.type.text"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="template", to="applications.app"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_templatemessages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "WhatsApp.data.templates.translaction.status.approved"),
                            ("IN_APPEAL", "WhatsApp.data.templates.translaction.status.in_appeal"),
                            ("PENDING", "WhatsApp.data.templates.translaction.status.pending"),
                            ("REJECTED", "WhatsApp.data.templates.translaction.status.rejected"),
                            ("PENDING_DELETION", "WhatsApp.data.templates.translaction.status.pending_deletion"),
                            ("DELETED", "WhatsApp.data.templates.translaction.status.deleted"),
                            ("DISABLED", "WhatsApp.data.templates.translaction.status.disabled"),
                            ("LOCKED", "WhatsApp.data.templates.translaction.status.locked"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("body", models.CharField(max_length=1024, null=True)),
                ("footer", models.CharField(max_length=60, null=True)),
                ("variable_count", models.IntegerField(null=True)),
                ("language", models.CharField(max_length=60, null=True)),
                ("country", models.CharField(max_length=60, null=True)),
                ("namespace", models.CharField(max_length=60, null=True)),
                ("external_id", models.CharField(max_length=60, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="wpp_templates.templatemessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateHeader",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "header_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "WhatsApp.data.templates.header.types.text"),
                            ("IMAGE", "WhatsApp.data.templates.header.types.image"),
                            ("DOCUMENT", "WhatsApp.data.templates.header.types.document"),
                            ("VIDEO", "WhatsApp.data.templates.header.types.video"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.CharField(default=None, max_length=60, null=True)),
                ("example", models.CharField(default=None, max_length=1024, null=True)),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headers",
                        to="wpp_templates.templatetranslation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateButton",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "button_type",
                    models.CharField(
                        choices=[
                            ("QUICK_REPLY", "WhatsApp.data.templates.buttons.type.quick_reply"),
                            ("PHONE_NUMBER", "WhatsApp.data.templates.buttons.type.phone_number"),
                            ("URL", "WhatsApp.data.templates.buttons.type.url"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.CharField(max_length=25, null=True)),
                ("country_code", models.IntegerField(null=True)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("url", models.CharField(max_length=2000, null=True)),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buttons",
                        to="wpp_templates.templatetranslation",
                    ),
                ),
            ],
        ),
    ]
