# Generated by Django 3.2.4 on 2022-09-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpp_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatebutton',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
