# Generated by Django 3.2.4 on 2022-09-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpp_templates', '0002_alter_templatebutton_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatebutton',
            name='url',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
