# Generated by Django 3.2.4 on 2022-09-26 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wpp_templates', '0002_auto_20220922_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateheader',
            name='text',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='templateheader',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header', to='wpp_templates.templatetranslation'),
        ),
    ]
