# Generated by Django 3.2.4 on 2022-10-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpp_templates', '0003_alter_templatemessage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templateheader',
            old_name='example',
            new_name='media',
        ),
    ]
