# Generated by Django 3.2.4 on 2022-09-26 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wpp_templates', '0003_auto_20220926_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateheader',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='wpp_templates.templatetranslation'),
        ),
    ]
