# Generated by Django 3.2.4 on 2023-05-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpp_templates', '0004_alter_templatebutton_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemessage',
            name='message_template_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='templatemessage',
            name='category',
            field=models.CharField(choices=[('ACCOUNT_UPDATE', 'WhatsApp.data.templates.category.account_update'), ('PAYMENT_UPDATE', 'WhatsApp.data.templates.category.payment_update'), ('PERSONAL_FINANCE_UPDATE', 'WhatsApp.data.templates.category.personal_finance_update'), ('SHIPPING_UPDATE', 'WhatsApp.data.templates.category.shipping_update'), ('RESERVATION_UPDATE', 'WhatsApp.data.templates.category.reservation_update'), ('ISSUE_RESOLUTION', 'WhatsApp.data.templates.category.issue_resolution'), ('APPOINTMENT_UPDATE', 'WhatsApp.data.templates.category.appointment_update'), ('TRANSPORTATION_UPDATE', 'WhatsApp.data.templates.category.transportation_update'), ('TICKET_UPDATE', 'WhatsApp.data.templates.category.ticket_update'), ('ALERT_UPDATE', 'WhatsApp.data.templates.category.alert_update'), ('AUTO_REPLY', 'WhatsApp.data.templates.category.auto_reply'), ('TRANSACTIONAL', 'WhatsApp.data.templates.category.transactional'), ('MARKETING', 'WhatsApp.data.templates.category.marketing'), ('OTP', 'WhatsApp.data.templates.category.otp'), ('UTILITY', 'WhatsApp.data.templates.category.utility'), ('AUTHENTICATION', 'WhatsApp.data.templates.category.authentication')], max_length=200),
        ),
    ]
