# Generated by Django 3.2.4 on 2022-10-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpp_templates', '0004_auto_20221005_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateheader',
            name='media',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='templateheader',
            name='text',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
