# Generated by Django 3.2.4 on 2022-09-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpp_templates', '0004_alter_templateheader_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateheader',
            name='example',
            field=models.CharField(default=None, max_length=512, null=True),
        ),
    ]
