<<<<<<< HEAD:marketplace/wpp_templates/migrations/0006_templatemessage_message_template_id.py
# Generated by Django 3.2.4 on 2023-05-24 19:29
=======
# Generated by Django 3.2.4 on 2023-05-29 18:08
>>>>>>> 430b35c6d17839a188ebb20ee37c95b17e503d0b:marketplace/wpp_templates/migrations/0006_templatetranslation_message_template_id.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpp_templates', '0005_alter_templatemessage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetranslation',
            name='message_template_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
