# Generated by Django 3.2.4 on 2022-09-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpp_templates', '0005_templateheader_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateheader',
            name='example',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
