# Generated by Django 3.2.4 on 2022-09-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpp_templates', '0006_alter_templateheader_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatetranslation',
            name='body',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='templatetranslation',
            name='country',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='templatetranslation',
            name='external_id',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='templatetranslation',
            name='footer',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='templatetranslation',
            name='language',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='templatetranslation',
            name='namespace',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='templatetranslation',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'WhatsApp.data.templates.translaction.status.approved'), ('IN_APPEAL', 'WhatsApp.data.templates.translaction.status.in_appeal'), ('PENDING', 'WhatsApp.data.templates.translaction.status.pending'), ('REJECTED', 'WhatsApp.data.templates.translaction.status.rejected'), ('PENDING_DELETION', 'WhatsApp.data.templates.translaction.status.pending_deletion'), ('DELETED', 'WhatsApp.data.templates.translaction.status.deleted'), ('DISABLED', 'WhatsApp.data.templates.translaction.status.disabled'), ('LOCKED', 'WhatsApp.data.templates.translaction.status.locked')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='templatetranslation',
            name='variable_count',
            field=models.IntegerField(null=True),
        ),
    ]
