# Generated by Django 3.2.4 on 2023-06-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpp_templates', '0006_templatetranslation_message_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetranslation',
            name='phone_number_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='templatetranslation',
            name='message_template_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
