# Generated by Django 3.2.4 on 2024-01-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0006_templatetranslation_message_template_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatetranslation",
            name="message_template_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
