# Generated by Django 3.2.4 on 2025-01-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0007_alter_templatetranslation_message_template_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatebutton",
            name="example",
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
