# Generated by Django 3.2.4 on 2022-09-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpp_templates', '0008_auto_20220929_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatebutton',
            name='text',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
