# Generated by Django 3.2.4 on 2025-03-31 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0017_alter_app_platform"),
        ("wpp_templates", "0008_templatebutton_example"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatemessage",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template",
                to="applications.app",
            ),
        ),
    ]
