# Generated by Django 3.2.4 on 2025-03-31 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0017_alter_app_platform"),
        ("wpp_templates", "0009_alter_templatemessage_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatemessage",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="applications.app",
            ),
        ),
    ]
