# Generated by Django 3.2.4 on 2025-05-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0010_alter_templatemessage_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatemessage",
            name="gallery_version",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
