# Generated by Django 3.2.4 on 2025-08-29 15:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0011_templatemessage_gallery_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetranslation",
            name="body_example",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
