# Generated by Django 3.2.4 on 2026-04-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_templates", "0012_templatetranslation_body_example"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatebutton",
            name="payment_setting",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="templatebutton",
            name="button_type",
            field=models.CharField(
                choices=[
                    ("QUICK_REPLY", "WhatsApp.data.templates.buttons.type.quick_reply"),
                    (
                        "PHONE_NUMBER",
                        "WhatsApp.data.templates.buttons.type.phone_number",
                    ),
                    ("URL", "WhatsApp.data.templates.buttons.type.url"),
                    (
                        "PAYMENT_REQUEST",
                        "WhatsApp.data.templates.buttons.type.payment_request",
                    ),
                ],
                max_length=20,
            ),
        ),
    ]
