# Generated by Django 3.2.4 on 2023-10-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalog",
            name="facebook_catalog_id",
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name="catalog",
            constraint=models.UniqueConstraint(
                fields=("facebook_catalog_id", "app"),
                name="unique_facebook_catalog_id_per_app",
            ),
        ),
    ]
