# Generated by Django 3.2.4 on 2023-11-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0016_app_configured"),
        ("wpp_products", "0002_auto_20231023_1051"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalog",
            name="vtex_app",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"code": "vtex"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vtex_catalogs",
                to="applications.app",
            ),
        ),
    ]
