# Generated by Django 3.2.4 on 2024-03-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_products", "0006_alter_productfeed_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="facebook_product_id",
            field=models.CharField(max_length=100),
        ),
    ]
