# Generated by Django 3.2.4 on 2024-04-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_products", "0007_alter_product_facebook_product_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku_id", models.IntegerField()),
                ("is_valid", models.BooleanField(default=True)),
                ("classification", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_validations",
                        to="wpp_products.catalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Validation",
                "verbose_name_plural": "Product Validations",
                "unique_together": {("catalog", "sku_id")},
            },
        ),
    ]
