# Generated by Django 3.2.4 on 2024-05-03 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_products", "0007_alter_product_facebook_product_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook_product_id", models.CharField(max_length=100)),
                ("data", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_catalog",
                        to="wpp_products.catalog",
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_feed",
                        to="wpp_products.productfeed",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="uploadproduct",
            index=models.Index(
                fields=["catalog", "feed", "status"],
                name="wpp_product_catalog_aca565_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="uploadproduct",
            index=models.Index(
                fields=["facebook_product_id"], name="wpp_product_faceboo_ec2ead_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadproduct",
            constraint=models.UniqueConstraint(
                fields=("facebook_product_id", "catalog"),
                name="unique_upload_facebook_product_id_per_catalog",
            ),
        ),
    ]
