# Generated by Django 3.2.4 on 2024-05-14 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0017_alter_app_platform"),
        ("wpp_products", "0008_auto_20240509_0007"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku_id", models.IntegerField()),
                ("data", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now=True)),
                (
                    "vtex_app",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"code": "vtex"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vtex_webhook_logs",
                        to="applications.app",
                    ),
                ),
            ],
        ),
    ]
