# Generated by Django 3.2.4 on 2024-05-15 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0017_alter_app_platform"),
        ("wpp_products", "0009_webhooklog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductUploadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku_id", models.IntegerField()),
                ("created_on", models.DateTimeField(auto_now=True)),
                (
                    "vtex_app",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"code": "vtex"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vtex_product_upload_logs",
                        to="applications.app",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="productuploadlog",
            index=models.Index(fields=["sku_id"], name="wpp_product_sku_id_7dda12_idx"),
        ),
        migrations.AddIndex(
            model_name="productuploadlog",
            index=models.Index(
                fields=["created_on"], name="wpp_product_created_bdfb44_idx"
            ),
        ),
    ]
