# Generated by Django 3.2.4 on 2024-06-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_products", "0010_auto_20240515_1158"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="additional_image_link",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="product",
            name="rich_text_description",
            field=models.TextField(blank=True, max_length=9999),
        ),
    ]
