# Generated by Django 3.2.4 on 2024-07-17 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_products", "0010_auto_20240515_1158"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="uploadproduct",
            name="unique_upload_facebook_product_id_per_catalog",
        ),
    ]
