# Generated by Django 3.2.4 on 2024-06-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_products", "0010_auto_20240515_1158"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku_id", models.IntegerField()),
                ("is_valid", models.BooleanField(default=True)),
                ("classification", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=9999, null=True),
                ),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_validations",
                        to="wpp_products.catalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Validation",
                "verbose_name_plural": "Product Validations",
            },
        ),
        migrations.AddIndex(
            model_name="productvalidation",
            index=models.Index(
                fields=["catalog"], name="wpp_product_catalog_ee2870_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvalidation",
            index=models.Index(fields=["sku_id"], name="wpp_product_sku_id_ff134b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productvalidation",
            unique_together={("catalog", "sku_id")},
        ),
    ]
