# Generated by Django 3.2.4 on 2024-10-07 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_products", "0011_auto_20240617_1310"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="uploadproduct",
            name="unique_upload_facebook_product_id_per_catalog",
        ),
    ]
