# Generated by Django 3.2.4 on 2025-06-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wpp_products",
            "0012_remove_uploadproduct_unique_upload_facebook_product_id_per_catalog",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadproduct",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
