# Generated by Django 3.2.4 on 2025-09-12 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wpp_products", "0013_uploadproduct_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadproduct",
            name="catalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upload_catalog",
                to="wpp_products.catalog",
            ),
        ),
        migrations.AlterField(
            model_name="uploadproduct",
            name="feed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upload_feed",
                to="wpp_products.productfeed",
            ),
        ),
    ]
